name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build and run services
      run: |
        docker-compose up -d
        sleep 10  # Give some time for services to start

    - name: Test JSON server
      run: curl http://localhost:3000 || exit 1

    - name: Test Cron server
      run: curl http://localhost:3001/cron/list || exit 1

    - name: Stop services
      run: docker-compose down