name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t modular-registry-checker .

    - name: Test Docker image
      run: |
        docker run -d -p 3000:3000 --name test-container modular-registry-checker
        sleep 5
        curl http://localhost:3000 || exit 1
        docker stop test-container