name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Build application
      run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t modular-registry-checker .

    - name: Test Docker image
      run: |
        docker run -d -p 3000:3000 --name test-container modular-registry-checker
        sleep 5
        curl http://localhost:3000
        docker stop test-container